# Generated by Django 4.2.27 on 2026-04-28 10:39

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('omnichannel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='action_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calllog',
            name='call_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='key_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calllog',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20),
        ),
        migrations.AddField(
            model_name='calllog',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='transcribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='transcript_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailintegration',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
