# Generated by Django 4.2.27 on 2026-05-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnichannel', '0002_calllog_action_items_calllog_call_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='emailintegration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='phoneintegration',
            options={'ordering': ['-created_at']},
        ),
    ]
