# Generated by Django 4.2.27 on 2026-04-27 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_role_profile_organizationmember_rbac_profile_and_more'),
        ('crm', '0006_contact_score_lead_score_scoringrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Used in the portal URL (e.g., client-portal)', unique=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='portals/logos/')),
                ('theme_color', models.CharField(default='#2563EB', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_deals', models.BooleanField(default=True)),
                ('allow_invoices', models.BooleanField(default=True)),
                ('allow_profile_edit', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortalMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access', to='crm.contact')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='portals.portal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'portal'], name='portals_por_user_id_cf5bcd_idx')],
                'unique_together': {('portal', 'user')},
            },
        ),
    ]
