# Generated by Django 4.2.27 on 2026-05-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portal',
            options={'ordering': ['-created_at']},
        ),
    ]
