# Generated by Django 4.2.27 on 2026-07-07 11:19

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_oauthapplication_oauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='oauthapplication',
            name='allowed_scopes',
            field=models.JSONField(blank=True, default=apps.users.models.default_oauth_scopes),
        ),
    ]
