# Generated by Django 4.2.27 on 2026-05-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_webform_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='campaignmember',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='webform',
            options={'ordering': ['-created_at']},
        ),
    ]
