# Generated by Django 4.2.27 on 2026-04-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_profile_organizationmember_rbac_profile_and_more'),
        ('billing', '0002_alter_invoice_tenant_alter_usagerecord_tenant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='BillingInvoice',
        ),
    ]
