# Generated by Django 4.2.27 on 2026-05-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_invoice_billinginvoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billinginvoice',
            options={'ordering': ['-created_at']},
        ),
    ]
