# Generated by Django 4.2.27 on 2026-05-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pricebook',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-created_at']},
        ),
    ]
