# Generated by Django 4.2.18 on 2026-02-03 08:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('secret', models.CharField(editable=False, max_length=64)),
                ('events', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('failing', 'Failing')], default='active', max_length=20)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='users.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('is_success', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.webhookendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
