# Generated by Django 4.2.27 on 2026-05-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_webhookendpoint_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookendpoint',
            options={'ordering': ['-created_at']},
        ),
    ]
