# Generated by Django 4.2.27 on 2026-04-27 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_blueprint_blueprintstate_blueprinttransition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='false_next_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='false_previous_nodes', to='workflows.workflownode'),
        ),
    ]
