# Generated by Django 4.2.27 on 2026-04-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflownode_false_next_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='controlled_field',
            field=models.CharField(blank=True, help_text="Field name on the target model that transitions update. E.g. 'stage_id' or 'status'", max_length=100),
        ),
    ]
