# Generated by Django 4.2.27 on 2026-05-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_blueprint_controlled_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blueprint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['-created_at']},
        ),
    ]
