# Generated by Django 4.2.27 on 2026-02-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_activity_due_date_activity_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
