# Generated by Django 4.2.27 on 2026-04-27 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_profile_organizationmember_rbac_profile_and_more'),
        ('crm', '0005_territory_assignmentrule_company_territories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('target_model', models.CharField(choices=[('lead', 'Lead'), ('contact', 'Contact')], max_length=20)),
                ('criteria', models.JSONField(default=dict)),
                ('score_change', models.IntegerField(default=10, help_text='Points to add (e.g., 10) or subtract (e.g., -5)')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppliedScoringRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_model', models.CharField(max_length=50)),
                ('record_id', models.UUIDField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_records', to='crm.scoringrule')),
            ],
            options={
                'indexes': [models.Index(fields=['record_model', 'record_id'], name='crm_applied_record__0e48f4_idx')],
                'unique_together': {('rule', 'record_model', 'record_id')},
            },
        ),
    ]
