# Generated by Django 4.2.27 on 2026-04-27 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0006_contact_score_lead_score_scoringrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritoryMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('manager', 'Manager')], default='member', max_length=20)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crm.territory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('territory', 'user')},
            },
        ),
    ]
