# Generated by Django 4.2.27 on 2026-04-28 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_profile_organizationmember_rbac_profile_and_more'),
        ('crm', '0007_territorymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AINextAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('target_model', models.CharField(choices=[('lead', 'Lead'), ('deal', 'Deal')], max_length=20)),
                ('target_id', models.UUIDField()),
                ('suggestion', models.TextField()),
                ('reasoning', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organization')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['target_model', 'target_id'], name='crm_ainexta_target__503529_idx')],
            },
        ),
    ]
