# Generated by Django 4.2.27 on 2026-05-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_ainextaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='scoringrule',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='territory',
            options={'ordering': ['-created_at']},
        ),
    ]
