# Generated by Django 4.2.27 on 2026-07-03 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_activity_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
