# Generated by Django 4.2.27 on 2026-04-28 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_profile_organizationmember_rbac_profile_and_more'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('projected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('confidence_interval', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.organization')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
